# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    OpenAPI spec version: v1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import freedompay_client
from freedompay_client.models.google_pay_init_request import GooglePayInitRequest  # noqa: E501
from freedompay_client.rest import ApiException


class TestGooglePayInitRequest(unittest.TestCase):
    """GooglePayInitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGooglePayInitRequest(self):
        """Test GooglePayInitRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = freedompay_client.models.google_pay_init_request.GooglePayInitRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
