# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from freedompay_client.models.card import Card  # noqa: E501

class TestCard(unittest.TestCase):
    """Card unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Card:
        """Test Card
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Card`
        """
        model = Card()  # noqa: E501
        if include_optional:
            return Card(
                account_number = '',
                account_type = '',
                card_type = '',
                token_subtype = '',
                subtype = '',
                issuer = '',
                cv_indicator = '',
                cv_number = '',
                expiration_month = '',
                expiration_year = '',
                issue_number = '',
                name_on_card = '',
                start_month = '',
                start_year = '',
                service_restriction_code = '',
                pin_ksn = '',
                pin_block = '',
                voucher_number = '',
                expected_brand = '',
                pl_data1 = '',
                pl_data2 = '',
                var_pass = ''
            )
        else:
            return Card(
        )
        """

    def testCard(self):
        """Test Card"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
