# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from freedompay_client.models.cc_auth_service import CCAuthService  # noqa: E501

class TestCCAuthService(unittest.TestCase):
    """CCAuthService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CCAuthService:
        """Test CCAuthService
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CCAuthService`
        """
        model = CCAuthService()  # noqa: E501
        if include_optional:
            return CCAuthService(
                trans_type = '',
                cof_indicator = '',
                cof_compliance_data = '',
                allow_partial = '',
                return_balance = '',
                auth_type = '',
                verbal_auth_code = '',
                ecom3ds = '',
                cavv = '',
                xid = '',
                orig_auth_amount = '',
                enable_avs = '',
                offline = '',
                offline_code = '',
                estimated = '',
                installment_number = '',
                installment_count = '',
                auth3dsformat = '',
                auth3dsjson = '',
                sca_exemptions = '',
                sca_upgrade = '',
                request_par = '',
                bill_payment = '',
                recurring = '',
                commerce_indicator = '',
                partial_payment_id = '',
                last_payment_flag = '',
                industry_datatype = '',
                run = ''
            )
        else:
            return CCAuthService(
        )
        """

    def testCCAuthService(self):
        """Test CCAuthService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
