# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from freedompay_client.models.cc_credit_service import CCCreditService  # noqa: E501

class TestCCCreditService(unittest.TestCase):
    """CCCreditService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CCCreditService:
        """Test CCCreditService
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CCCreditService`
        """
        model = CCCreditService()  # noqa: E501
        if include_optional:
            return CCCreditService(
                trans_type = '',
                offline = '',
                offline_code = '',
                return_balance = '',
                business_date = '',
                bill_payment = '',
                recurring = '',
                commerce_indicator = '',
                partial_payment_id = '',
                last_payment_flag = '',
                industry_datatype = '',
                run = ''
            )
        else:
            return CCCreditService(
        )
        """

    def testCCCreditService(self):
        """Test CCCreditService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
