# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    OpenAPI spec version: v1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import freedompay_client
from freedompay_client.api.controls_api import ControlsApi  # noqa: E501
from freedompay_client.rest import ApiException


class TestControlsApi(unittest.TestCase):
    """ControlsApi unit test stubs"""

    def setUp(self):
        self.api = freedompay_client.api.controls_api.ControlsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_controls_init_v15(self):
        """Test case for controls_init_v15

        Initializes a payment request workflow.  # noqa: E501
        """
        pass

    def test_controls_init_v15_0(self):
        """Test case for controls_init_v15_0

        Initializes a PayPal payment request workflow.  # noqa: E501
        """
        pass

    def test_controls_init_v15_1(self):
        """Test case for controls_init_v15_1

        Initializes a PayByBank payment request workflow.  # noqa: E501
        """
        pass

    def test_init_apple_pay(self):
        """Test case for init_apple_pay

        Initializes an ApplePay payment request workflow.  # noqa: E501
        """
        pass

    def test_init_google_pay(self):
        """Test case for init_google_pay

        Initializes a Google Pay payment request workflow.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
