# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from freedompay_client.models.ship_to import ShipTo  # noqa: E501

class TestShipTo(unittest.TestCase):
    """ShipTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShipTo:
        """Test ShipTo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShipTo`
        """
        model = ShipTo()  # noqa: E501
        if include_optional:
            return ShipTo(
                company = '',
                title = '',
                first_name = '',
                middle_name = '',
                last_name = '',
                suffix = '',
                street1 = '',
                street2 = '',
                street3 = '',
                street4 = '',
                city = '',
                state = '',
                postal_code = '',
                country = '',
                phone_number = '',
                fax_number = '',
                email = '',
                ssn = '',
                date_of_birth = '',
                shipping_company = '',
                shipping_method = '',
                tracking_number = ''
            )
        else:
            return ShipTo(
        )
        """

    def testShipTo(self):
        """Test ShipTo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
