# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from freedompay_client.models.google_billing_address_request import GoogleBillingAddressRequest  # noqa: E501

class TestGoogleBillingAddressRequest(unittest.TestCase):
    """GoogleBillingAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleBillingAddressRequest:
        """Test GoogleBillingAddressRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleBillingAddressRequest`
        """
        model = GoogleBillingAddressRequest()  # noqa: E501
        if include_optional:
            return GoogleBillingAddressRequest(
                format = 'Unknown',
                is_required = True,
                is_phone_number_required = True
            )
        else:
            return GoogleBillingAddressRequest(
        )
        """

    def testGoogleBillingAddressRequest(self):
        """Test GoogleBillingAddressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
