# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freedompay_client.api.payments_api import PaymentsApi  # noqa: E501


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_payments_acknowledge(self) -> None:
        """Test case for payments_acknowledge

        """
        pass

    def test_payments_post_v13(self) -> None:
        """Test case for payments_post_v13

        """
        pass

    def test_payments_reverse(self) -> None:
        """Test case for payments_reverse

        """
        pass


if __name__ == '__main__':
    unittest.main()
