# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from freedompay_client.models.invoice_header import InvoiceHeader  # noqa: E501

class TestInvoiceHeader(unittest.TestCase):
    """InvoiceHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceHeader:
        """Test InvoiceHeader
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceHeader`
        """
        model = InvoiceHeader()  # noqa: E501
        if include_optional:
            return InvoiceHeader(
                invoice_number = '',
                invoice_date = '',
                merchant_descriptor = '',
                merchant_descriptor_contact = '',
                merchant_descriptor_url = '',
                purchaser_code = '',
                purchaser_order_date = '',
                goods_indicator = '',
                customer_po = '',
                product_code_standard = '',
                eid_indicator = ''
            )
        else:
            return InvoiceHeader(
        )
        """

    def testInvoiceHeader(self):
        """Test InvoiceHeader"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
