# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    The version of the OpenAPI document: v1.5
    Generated by: https://openapi-generator.tech
"""

from freedompay-client.paths.v1_5_payments_acknowledge.post import PaymentsAcknowledge
from freedompay-client.paths.v1_5_payments.post import PaymentsPostV13
from freedompay-client.paths.v1_5_payments_reverse.post import PaymentsReverse


class PaymentsApi(
    PaymentsAcknowledge,
    PaymentsPostV13,
    PaymentsReverse,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
