# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    The version of the OpenAPI document: v1.5
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from freedompay-client import schemas  # noqa: F401


class AcknowledgeRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            PosSyncAttemptNum = schemas.Int32Schema
            PosSyncId = schemas.StrSchema
            __annotations__ = {
                "PosSyncAttemptNum": PosSyncAttemptNum,
                "PosSyncId": PosSyncId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PosSyncAttemptNum"]) -> MetaOapg.properties.PosSyncAttemptNum: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PosSyncId"]) -> MetaOapg.properties.PosSyncId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["PosSyncAttemptNum", "PosSyncId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PosSyncAttemptNum"]) -> typing.Union[MetaOapg.properties.PosSyncAttemptNum, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PosSyncId"]) -> typing.Union[MetaOapg.properties.PosSyncId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["PosSyncAttemptNum", "PosSyncId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        PosSyncAttemptNum: typing.Union[MetaOapg.properties.PosSyncAttemptNum, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        PosSyncId: typing.Union[MetaOapg.properties.PosSyncId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AcknowledgeRequest':
        return super().__new__(
            cls,
            *args,
            PosSyncAttemptNum=PosSyncAttemptNum,
            PosSyncId=PosSyncId,
            _configuration=_configuration,
            **kwargs,
        )
