# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    The version of the OpenAPI document: v1.5
    Generated by: https://openapi-generator.tech
"""

import unittest

import freedompay-client
from freedompay-client.model.expiration_date_control import ExpirationDateControl
from freedompay-client import configuration


class TestExpirationDateControl(unittest.TestCase):
    """ExpirationDateControl unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
