# coding: utf-8

# flake8: noqa

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    The version of the OpenAPI document: v1.5
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.5.0"

# import ApiClient
from freedompay-client.api_client import ApiClient

# import Configuration
from freedompay-client.configuration import Configuration

# import exceptions
from freedompay-client.exceptions import OpenApiException
from freedompay-client.exceptions import ApiAttributeError
from freedompay-client.exceptions import ApiTypeError
from freedompay-client.exceptions import ApiValueError
from freedompay-client.exceptions import ApiKeyError
from freedompay-client.exceptions import ApiException
