# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class CCCreditService(BaseModel):
    """
    CCCreditService
    """
    trans_type: Optional[StrictStr] = Field(None, alias="transType")
    offline: Optional[StrictStr] = None
    offline_code: Optional[StrictStr] = Field(None, alias="offlineCode")
    return_balance: Optional[StrictStr] = Field(None, alias="returnBalance")
    business_date: Optional[StrictStr] = Field(None, alias="businessDate")
    bill_payment: Optional[StrictStr] = Field(None, alias="billPayment")
    recurring: Optional[StrictStr] = None
    commerce_indicator: Optional[StrictStr] = Field(None, alias="commerceIndicator")
    partial_payment_id: Optional[StrictStr] = Field(None, alias="partialPaymentId")
    last_payment_flag: Optional[StrictStr] = Field(None, alias="lastPaymentFlag")
    industry_datatype: Optional[StrictStr] = Field(None, alias="industryDatatype")
    run: Optional[StrictStr] = None
    __properties = ["transType", "offline", "offlineCode", "returnBalance", "businessDate", "billPayment", "recurring", "commerceIndicator", "partialPaymentId", "lastPaymentFlag", "industryDatatype", "run"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CCCreditService:
        """Create an instance of CCCreditService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CCCreditService:
        """Create an instance of CCCreditService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CCCreditService.parse_obj(obj)

        _obj = CCCreditService.parse_obj({
            "trans_type": obj.get("transType"),
            "offline": obj.get("offline"),
            "offline_code": obj.get("offlineCode"),
            "return_balance": obj.get("returnBalance"),
            "business_date": obj.get("businessDate"),
            "bill_payment": obj.get("billPayment"),
            "recurring": obj.get("recurring"),
            "commerce_indicator": obj.get("commerceIndicator"),
            "partial_payment_id": obj.get("partialPaymentId"),
            "last_payment_flag": obj.get("lastPaymentFlag"),
            "industry_datatype": obj.get("industryDatatype"),
            "run": obj.get("run")
        })
        return _obj


