# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class ConsumerAuthentication(BaseModel):
    """
    ConsumerAuthentication
    """
    enabled: Optional[StrictBool] = Field(None, alias="Enabled")
    auto_map_to_free_way_request: Optional[StrictBool] = Field(None, alias="AutoMapToFreeWayRequest")
    fields: Optional[Dict[str, StrictStr]] = Field(None, alias="Fields")
    __properties = ["Enabled", "AutoMapToFreeWayRequest", "Fields"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConsumerAuthentication:
        """Create an instance of ConsumerAuthentication from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConsumerAuthentication:
        """Create an instance of ConsumerAuthentication from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConsumerAuthentication.parse_obj(obj)

        _obj = ConsumerAuthentication.parse_obj({
            "enabled": obj.get("Enabled"),
            "auto_map_to_free_way_request": obj.get("AutoMapToFreeWayRequest"),
            "fields": obj.get("Fields")
        })
        return _obj


