# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    OpenAPI spec version: v1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from freedompay_client.configuration import Configuration


class FraudCheckOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'kount': 'KountOptions'
    }

    attribute_map = {
        'enabled': 'Enabled',
        'kount': 'Kount'
    }

    def __init__(self, enabled=None, kount=None, _configuration=None):  # noqa: E501
        """FraudCheckOptions - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._enabled = None
        self._kount = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if kount is not None:
            self.kount = kount

    @property
    def enabled(self):
        """Gets the enabled of this FraudCheckOptions.  # noqa: E501


        :return: The enabled of this FraudCheckOptions.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this FraudCheckOptions.


        :param enabled: The enabled of this FraudCheckOptions.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def kount(self):
        """Gets the kount of this FraudCheckOptions.  # noqa: E501


        :return: The kount of this FraudCheckOptions.  # noqa: E501
        :rtype: KountOptions
        """
        return self._kount

    @kount.setter
    def kount(self, kount):
        """Sets the kount of this FraudCheckOptions.


        :param kount: The kount of this FraudCheckOptions.  # noqa: E501
        :type: KountOptions
        """

        self._kount = kount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FraudCheckOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FraudCheckOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FraudCheckOptions):
            return True

        return self.to_dict() != other.to_dict()
