# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from freedompay_client.models.incentive_incentive import IncentiveIncentive

class IncentiveService(BaseModel):
    """
    IncentiveService
    """
    system_id: Optional[StrictStr] = Field(None, alias="systemId")
    consumer_identifier_type: Optional[StrictStr] = Field(None, alias="consumerIdentifierType")
    consumer_identifier: Optional[StrictStr] = Field(None, alias="consumerIdentifier")
    additional_data: Optional[StrictStr] = Field(None, alias="additionalData")
    additional_data_type: Optional[StrictStr] = Field(None, alias="additionalDataType")
    incentives: Optional[conlist(IncentiveIncentive)] = None
    trans_type: Optional[StrictStr] = Field(None, alias="transType")
    run: Optional[StrictStr] = None
    __properties = ["systemId", "consumerIdentifierType", "consumerIdentifier", "additionalData", "additionalDataType", "incentives", "transType", "run"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IncentiveService:
        """Create an instance of IncentiveService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in incentives (list)
        _items = []
        if self.incentives:
            for _item in self.incentives:
                if _item:
                    _items.append(_item.to_dict())
            _dict['incentives'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IncentiveService:
        """Create an instance of IncentiveService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IncentiveService.parse_obj(obj)

        _obj = IncentiveService.parse_obj({
            "system_id": obj.get("systemId"),
            "consumer_identifier_type": obj.get("consumerIdentifierType"),
            "consumer_identifier": obj.get("consumerIdentifier"),
            "additional_data": obj.get("additionalData"),
            "additional_data_type": obj.get("additionalDataType"),
            "incentives": [IncentiveIncentive.from_dict(_item) for _item in obj.get("incentives")] if obj.get("incentives") is not None else None,
            "trans_type": obj.get("transType"),
            "run": obj.get("run")
        })
        return _obj


