# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class LoyaltyService(BaseModel):
    """
    LoyaltyService
    """
    card_type: Optional[StrictStr] = Field(None, alias="cardType")
    card_number: Optional[StrictStr] = Field(None, alias="cardNumber")
    app_id: Optional[StrictStr] = Field(None, alias="appId")
    id_block: Optional[StrictStr] = Field(None, alias="idBlock")
    id_ksn: Optional[StrictStr] = Field(None, alias="idKsn")
    run: Optional[StrictStr] = None
    __properties = ["cardType", "cardNumber", "appId", "idBlock", "idKsn", "run"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LoyaltyService:
        """Create an instance of LoyaltyService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LoyaltyService:
        """Create an instance of LoyaltyService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LoyaltyService.parse_obj(obj)

        _obj = LoyaltyService.parse_obj({
            "card_type": obj.get("cardType"),
            "card_number": obj.get("cardNumber"),
            "app_id": obj.get("appId"),
            "id_block": obj.get("idBlock"),
            "id_ksn": obj.get("idKsn"),
            "run": obj.get("run")
        })
        return _obj


