# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5

    The version of the OpenAPI document: v1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class OfflineControl(BaseModel):
    """
    OfflineControl
    """
    dtk: Optional[StrictStr] = None
    retry_count: Optional[StrictStr] = Field(None, alias="retryCount")
    internal_ffw: Optional[StrictStr] = None
    saf_request_id: Optional[StrictStr] = Field(None, alias="safRequestId")
    saf_system_id: Optional[StrictStr] = Field(None, alias="safSystemId")
    __properties = ["dtk", "retryCount", "internal_ffw", "safRequestId", "safSystemId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OfflineControl:
        """Create an instance of OfflineControl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OfflineControl:
        """Create an instance of OfflineControl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OfflineControl.parse_obj(obj)

        _obj = OfflineControl.parse_obj({
            "dtk": obj.get("dtk"),
            "retry_count": obj.get("retryCount"),
            "internal_ffw": obj.get("internal_ffw"),
            "saf_request_id": obj.get("safRequestId"),
            "saf_system_id": obj.get("safSystemId")
        })
        return _obj


