# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    OpenAPI spec version: v1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from freedompay_client.configuration import Configuration


class RestaurantData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'food_subtotal': 'str',
        'beverage_subtotal': 'str'
    }

    attribute_map = {
        'food_subtotal': 'foodSubtotal',
        'beverage_subtotal': 'beverageSubtotal'
    }

    def __init__(self, food_subtotal=None, beverage_subtotal=None, _configuration=None):  # noqa: E501
        """RestaurantData - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._food_subtotal = None
        self._beverage_subtotal = None
        self.discriminator = None

        if food_subtotal is not None:
            self.food_subtotal = food_subtotal
        if beverage_subtotal is not None:
            self.beverage_subtotal = beverage_subtotal

    @property
    def food_subtotal(self):
        """Gets the food_subtotal of this RestaurantData.  # noqa: E501


        :return: The food_subtotal of this RestaurantData.  # noqa: E501
        :rtype: str
        """
        return self._food_subtotal

    @food_subtotal.setter
    def food_subtotal(self, food_subtotal):
        """Sets the food_subtotal of this RestaurantData.


        :param food_subtotal: The food_subtotal of this RestaurantData.  # noqa: E501
        :type: str
        """

        self._food_subtotal = food_subtotal

    @property
    def beverage_subtotal(self):
        """Gets the beverage_subtotal of this RestaurantData.  # noqa: E501


        :return: The beverage_subtotal of this RestaurantData.  # noqa: E501
        :rtype: str
        """
        return self._beverage_subtotal

    @beverage_subtotal.setter
    def beverage_subtotal(self, beverage_subtotal):
        """Sets the beverage_subtotal of this RestaurantData.


        :param beverage_subtotal: The beverage_subtotal of this RestaurantData.  # noqa: E501
        :type: str
        """

        self._beverage_subtotal = beverage_subtotal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RestaurantData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RestaurantData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RestaurantData):
            return True

        return self.to_dict() != other.to_dict()
