# coding: utf-8

"""
    Hosted Payment Controls API Documentation v1.5

    The API for Hosted Payment Controls. To access the swagger.json file open the following link: https://hpc.uat.freedompay.com/api/swagger/docs/v1.5  # noqa: E501

    OpenAPI spec version: v1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from freedompay_client.configuration import Configuration


class TokenCreateService(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'disable_verification': 'str',
        'pos_data': 'str',
        'dyn_exp': 'str',
        'run': 'str'
    }

    attribute_map = {
        'type': 'type',
        'disable_verification': 'disableVerification',
        'pos_data': 'posData',
        'dyn_exp': 'dynExp',
        'run': 'run'
    }

    def __init__(self, type=None, disable_verification=None, pos_data=None, dyn_exp=None, run=None, _configuration=None):  # noqa: E501
        """TokenCreateService - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._type = None
        self._disable_verification = None
        self._pos_data = None
        self._dyn_exp = None
        self._run = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if disable_verification is not None:
            self.disable_verification = disable_verification
        if pos_data is not None:
            self.pos_data = pos_data
        if dyn_exp is not None:
            self.dyn_exp = dyn_exp
        if run is not None:
            self.run = run

    @property
    def type(self):
        """Gets the type of this TokenCreateService.  # noqa: E501


        :return: The type of this TokenCreateService.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TokenCreateService.


        :param type: The type of this TokenCreateService.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def disable_verification(self):
        """Gets the disable_verification of this TokenCreateService.  # noqa: E501


        :return: The disable_verification of this TokenCreateService.  # noqa: E501
        :rtype: str
        """
        return self._disable_verification

    @disable_verification.setter
    def disable_verification(self, disable_verification):
        """Sets the disable_verification of this TokenCreateService.


        :param disable_verification: The disable_verification of this TokenCreateService.  # noqa: E501
        :type: str
        """

        self._disable_verification = disable_verification

    @property
    def pos_data(self):
        """Gets the pos_data of this TokenCreateService.  # noqa: E501


        :return: The pos_data of this TokenCreateService.  # noqa: E501
        :rtype: str
        """
        return self._pos_data

    @pos_data.setter
    def pos_data(self, pos_data):
        """Sets the pos_data of this TokenCreateService.


        :param pos_data: The pos_data of this TokenCreateService.  # noqa: E501
        :type: str
        """

        self._pos_data = pos_data

    @property
    def dyn_exp(self):
        """Gets the dyn_exp of this TokenCreateService.  # noqa: E501


        :return: The dyn_exp of this TokenCreateService.  # noqa: E501
        :rtype: str
        """
        return self._dyn_exp

    @dyn_exp.setter
    def dyn_exp(self, dyn_exp):
        """Sets the dyn_exp of this TokenCreateService.


        :param dyn_exp: The dyn_exp of this TokenCreateService.  # noqa: E501
        :type: str
        """

        self._dyn_exp = dyn_exp

    @property
    def run(self):
        """Gets the run of this TokenCreateService.  # noqa: E501


        :return: The run of this TokenCreateService.  # noqa: E501
        :rtype: str
        """
        return self._run

    @run.setter
    def run(self, run):
        """Sets the run of this TokenCreateService.


        :param run: The run of this TokenCreateService.  # noqa: E501
        :type: str
        """

        self._run = run

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenCreateService, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenCreateService):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenCreateService):
            return True

        return self.to_dict() != other.to_dict()
